/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-clients`; params?: Router.UnknownInputParams; } | { pathname: `/admin-finance`; params?: Router.UnknownInputParams; } | { pathname: `/admin-history`; params?: Router.UnknownInputParams; } | { pathname: `/admin-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/barbers`; params?: Router.UnknownInputParams; } | { pathname: `/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/customer`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin-clients`; params?: Router.UnknownOutputParams; } | { pathname: `/admin-finance`; params?: Router.UnknownOutputParams; } | { pathname: `/admin-history`; params?: Router.UnknownOutputParams; } | { pathname: `/admin-schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/barbers`; params?: Router.UnknownOutputParams; } | { pathname: `/confirmation`; params?: Router.UnknownOutputParams; } | { pathname: `/customer`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/services`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin-clients${`?${string}` | `#${string}` | ''}` | `/admin-finance${`?${string}` | `#${string}` | ''}` | `/admin-history${`?${string}` | `#${string}` | ''}` | `/admin-schedule${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/barbers${`?${string}` | `#${string}` | ''}` | `/confirmation${`?${string}` | `#${string}` | ''}` | `/customer${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin-clients`; params?: Router.UnknownInputParams; } | { pathname: `/admin-finance`; params?: Router.UnknownInputParams; } | { pathname: `/admin-history`; params?: Router.UnknownInputParams; } | { pathname: `/admin-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/barbers`; params?: Router.UnknownInputParams; } | { pathname: `/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `/customer`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
